export const FETCH_TASKS_REQUEST = "FETCH_TASKS_REQUEST";
export const FETCH_TASKS_SUCCESS = "FETCH_TASKS_SUCCESS";
export const FETCH_TASKS_FAILED = "FETCH_TASKS_FAILED";

export const SHOW_LOADING = "SHOW_LOADING";
export const HIDE_LOADING = "HIDE_LOADING";

export const FILTER_TASK = "FILTER_TASK";
export const FILTER_TASK_SUCCESS = "FILTER_TASK_SUCCESS";

export const SHOW_MODAL = "SHOW_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";
export const CHANGE_MODAL_TITLE = "CHANGE_MODAL_TITLE";
export const CHANGE_MODAL_CONTENT = "CHANGE_MODAL_CONTENT";

export const ADD_TASK_REQUEST = "ADD_TASK_REQUEST_";
export const ADD_TASKS_SUCCESS = "ADD_TASKS_SUCCESS";
export const ADD_TASKS_FAILED = "ADD_TASKS_FAILED";

export const TASK_EDITING = "TASK_EDITING";

export const UPDATE_TASK_REQUEST = "UPDATE_TASK_REQUEST_";
export const UPDATE_TASK_SUCCESS = "UPDATE_TASK_SUCCESS";
export const UPDATE_TASK_FAILED = "UPDATE_TASK_FAILED";

export const REMOVE_TASK_REQUEST = "REMOVE_TASK_REQUEST_";
export const REMOVE_TASK_SUCCESS = "REMOVE_TASK_SUCCESS";
export const REMOVE_TASK_FAILED = "REMOVE_TASK_FAILED";
